name: Build ubuntu 2404 with packer and upload to vagrant cloud
on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      - "main"
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab

jobs:
  packer:
    name: Build image and upload it to vagrant cloud
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest
      - name: Install vagrant
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install vagrant
      - name: Packer Init
        run: packer init .
      - name: Packer Build - Branches
        run: packer build .
      - name: Packer Build - Branches
        run: packer validate .

